server:
  address: 0.0.0.0
  port: ${PORT:5000}

spring:
  config:
    activate:
      on-profile: prod
    import: "aws-parameterstore:/config/safely/"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url, username, password는 AWS SSM에서 자동 주입

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      # host, port, password는 SSM에서 자동 주입
      ssl:
        enabled: true   # ElastiCache TLS 활성화
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

logging:
  level:
    org.springframework: INFO # 운영에서는 INFO 이상으로 하는 게 좋음
    com.safely: INFO