spring:
  application:
    name: safely

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev

cloud:
  aws:
    region:
      static: ap-northeast-2