limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;
limit_conn_zone $binary_remote_addr zone=addr:10m;

map $http_user_agent $bad_bot {
    default 0;
    ~*sqlmap 1;
    ~*nikto 1;
    ~*acunetix 1;
    ~*nmap 1;
    ~*masscan 1;
    ~*zgrab 1;
    ~*python-requests 1;
    ~*wget 1;
}